version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nest-demo
hooks:
  BeforeInstall:
    - location: scripts/codedeploy_before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/codedeploy_after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/codedeploy_application_start.sh
      timeout: 300
      runas: ec2-user
