version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Building NestJS application"
      - npm run build

artifacts:
  files:
    - '**/*' # Include all files in the artifact

cache:
  paths:
    - 'node_modules/**/*' # Cache the node_modules directory for faster builds
